/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.demowsdos;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author EduardoZetina
 */
public class mainForm extends javax.swing.JFrame {

    panIntro panInt = new panIntro();
    panUploadFiles panLoad = new panUploadFiles();
    panFileStatus panStatus = new panFileStatus();
    panLogin panLog =  new panLogin();
    panExit panExi =  new panExit();
    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        chargeTabs();
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage("src\\main\\java\\Miselaneous\\optiCat.png");
        //Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Miselaneous/optiCat.png"));
        //Before asign the new icon, we have to set up the "iconImage" property to "Value from existing component"
        //choosing the option "Property" to establish  it as "iconImage"
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        tabMain = new javax.swing.JTabbedPane();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabMain.setBackground(new java.awt.Color(0, 0, 0));
        tabMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabMain.setForeground(new java.awt.Color(228, 239, 22));
        tabMain.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(tabMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 711, 448));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
        
        
    }
    
   /* public interface BasicHttpBinding_IService extends java.rmi.Remote {
        
        Object obRes = getFileTypes(String strApiKey);
        throws java.rmi.RemoteException; //to manage wsdl:fault
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables

    private void chargeTabs() {
        

        panLoad =new panUploadFiles();
        panInt = new panIntro();
        tabMain.addTab("Introducton", panInt);
        tabMain.addTab("Upload files", panLoad);
        tabMain.addTab("File Status", panStatus);
        tabMain.addTab("Login  and Logout", panLog);
        tabMain.addTab("", panExi);
        //add button to exit
        JButton btnClose =  new JButton("Exit");
        btnClose.setBorder(null);
        btnClose.setFocusPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setPreferredSize(new Dimension(25,20));
        Font font = new Font("Tahoma", Font.BOLD, 11);
        btnClose.setFont(font);
        btnClose.addActionListener(new ActionListener(){
        
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        //btnclose.setFont(arg0);
        tabMain.setTabComponentAt(4, btnClose);
        
        
        tabMain.setSelectedComponent(panInt);
        
       
    }
}
