/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.demowsdos;


import com.company.wsdl.Filestatusresponse;
import com.company.wsdl.FilestatusresponseImportmessage;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EduardoZetina
 */
public class panFileStatus extends javax.swing.JPanel {
    
    public static DefaultTableModel table;
    public static String[] sstrValues= new String[9];

   
     
    /**
     * Creates new form panFileStatus
     */
    public panFileStatus() {
        initComponents();
        ImageIcon icon=new ImageIcon("src\\main\\java\\Miselaneous\\jaguar2.jpg");
        lblBacGro.setIcon(icon);
        
        txtComDat.setEditable(false);
        txtFilRecCou.setEditable(false);
        txtImRecCou.setEditable(false);
        txtImpErrCou.setEditable(false);
        txtImpWarCou.setEditable(false);
        txtSchErrCou.setEditable(false);
        txtStaDat.setEditable(false);
          
    }

    public void fillStatus(Filestatusresponse responseSatatus) {
         
        
        //fill Filds
        
        txtComDat.setText(responseSatatus.getCompletiondate());
        txtFilRecCou.setText(responseSatatus.getFilerecordcount());
        txtImRecCou.setText(responseSatatus.getImporterrorcount());
        txtImpErrCou.setText(responseSatatus.getImporterrorcount());
        txtImpWarCou.setText(responseSatatus.getImportwarningcount());
        txtSchErrCou.setText(responseSatatus.getSchemaerrorcount());
        txtStaDat.setText(responseSatatus.getStartdate());
        //create header   {"","",""}
         //String[] strheader =  new String[]{"Message Type", "Date", "Message"};
         String[] strRecords = new String[3];

        for(FilestatusresponseImportmessage responseMessage : responseSatatus.getImportmessages())
        {
           //fill table   
           strRecords[0] = responseMessage.getMessagetype();
           strRecords[1] = responseMessage.getTimeindex();
           strRecords[2] = responseMessage.getMessage();
           table.addRow(strRecords);
        }
        
            //"aqui va el response" ver por que no permite registro, encabezado
            //table = new DefaultTableModel(strheader, 1);
            tblStatus.setModel(table);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtImRecCou = new javax.swing.JTextField();
        txtFilRecCou = new javax.swing.JTextField();
        txtImpWarCou = new javax.swing.JTextField();
        txtSchErrCou = new javax.swing.JTextField();
        txtStaDat = new javax.swing.JTextField();
        txtComDat = new javax.swing.JTextField();
        txtImpErrCou = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStatus = new javax.swing.JTable();
        lblBacGro = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(228, 239, 22));
        jLabel3.setText("Import Status:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 90, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(228, 239, 22));
        jLabel4.setText("File Record Count");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(228, 239, 22));
        jLabel5.setText("Import Warning Count");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 130, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(228, 239, 22));
        jLabel6.setText("Import Record Count");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, 120, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(228, 239, 22));
        jLabel7.setText("Schema Error Count");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 120, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setForeground(new java.awt.Color(228, 239, 22));
        jLabel8.setText("Start Date");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 103, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(228, 239, 22));
        jLabel9.setText("Completion Date");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 95, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setForeground(new java.awt.Color(228, 239, 22));
        jLabel10.setText("Import Error Count");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 103, -1));

        txtImRecCou.setBackground(new java.awt.Color(102, 102, 102));
        txtImRecCou.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtImRecCou.setForeground(new java.awt.Color(228, 239, 22));
        add(txtImRecCou, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 78, -1));

        txtFilRecCou.setBackground(new java.awt.Color(102, 102, 102));
        txtFilRecCou.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtFilRecCou.setForeground(new java.awt.Color(228, 239, 22));
        add(txtFilRecCou, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 78, -1));

        txtImpWarCou.setBackground(new java.awt.Color(102, 102, 102));
        txtImpWarCou.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtImpWarCou.setForeground(new java.awt.Color(228, 239, 22));
        add(txtImpWarCou, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 78, -1));

        txtSchErrCou.setBackground(new java.awt.Color(102, 102, 102));
        txtSchErrCou.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSchErrCou.setForeground(new java.awt.Color(228, 239, 22));
        add(txtSchErrCou, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 86, -1));

        txtStaDat.setBackground(new java.awt.Color(102, 102, 102));
        txtStaDat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtStaDat.setForeground(new java.awt.Color(228, 239, 22));
        add(txtStaDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 81, 86, -1));

        txtComDat.setBackground(new java.awt.Color(102, 102, 102));
        txtComDat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtComDat.setForeground(new java.awt.Color(228, 239, 22));
        add(txtComDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 112, 86, -1));

        txtImpErrCou.setBackground(new java.awt.Color(102, 102, 102));
        txtImpErrCou.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtImpErrCou.setForeground(new java.awt.Color(228, 239, 22));
        add(txtImpErrCou, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 86, -1));

        tblStatus.setBackground(new java.awt.Color(102, 102, 102));
        tblStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblStatus.setForeground(new java.awt.Color(228, 239, 22));
        tblStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message Type", "Date", "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStatus);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 638, 218));
        add(lblBacGro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 390));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBacGro;
    private javax.swing.JTable tblStatus;
    private javax.swing.JTextField txtComDat;
    private javax.swing.JTextField txtFilRecCou;
    private javax.swing.JTextField txtImRecCou;
    private javax.swing.JTextField txtImpErrCou;
    private javax.swing.JTextField txtImpWarCou;
    private javax.swing.JTextField txtSchErrCou;
    private javax.swing.JTextField txtStaDat;
    // End of variables declaration//GEN-END:variables
}
